#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org3
  labels:
    app: chaincode-basic-org3
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org3
    spec:
      nodeName: worker3
      containers:
        - image: 151996/basic-cc-hlf:1.0
          name: chaincode-basic-org3
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:b4fde13495664558343625d164bfb2a559ee6548a46fae36d0fd82f23fac061e"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
